--SQL Advance Case Study


--Q1--BEGIN 
	
	SELECT DISTINCT STATE FROM FACT_TRANSACTIONS AS T1
	INNER JOIN DIM_LOCATION AS T2
	ON T1.IDLocation = T2.IDLocation
	WHERE T1.DATE >= '2005'

--Q1--END

--Q2--BEGIN
	
	SELECT TOP 1 STATE FROM FACT_TRANSACTIONS AS T1
	INNER JOIN DIM_LOCATION AS T2
	ON T1.IDLocation = T2.IDLocation
	INNER JOIN DIM_MODEL AS T3
	INNER JOIN DIM_MANUFACTURER AS T4
	ON T3.IDManufacturer = T4.IDManufacturer
	ON T1.IDModel = T3.IDModel
	WHERE COUNTRY = 'US' AND Manufacturer_Name = 'Samsung'
	GROUP BY STATE
	ORDER BY SUM(Quantity) DESC

--Q2--END

--Q3--BEGIN      
	
	SELECT STATE,ZIPCODE, MODEL_NAME, COUNT(T2.IDMODEL) AS NO_OF_TRANSACTIONS FROM FACT_TRANSACTIONS AS T1
	INNER JOIN DIM_MODEL AS T2
	ON T1.IDModel = T2.IDModel
	INNER JOIN DIM_LOCATION AS T3
	ON T1.IDLocation = T3.IDLocation
	GROUP BY Model_Name, State, ZipCode

--Q3--END

--Q4--BEGIN

    SELECT TOP 1 MANUFACTURER_NAME, MODEL_NAME, UNIT_PRICE FROM DIM_MANUFACTURER AS T1
	INNER JOIN DIM_MODEL AS T2
	ON T1.IDManufacturer = T2.IDManufacturer
	ORDER BY Unit_price ASC

--Q4--END

--Q5--BEGIN

     SELECT TOP 5 MANUFACTURER_NAME, MODEL_NAME, AVG(TOTALPRICE) AS AVG_PRICE, SUM(TOTALPRICE) AS TOTAL_SALES, COUNT(QUANTITY) AS QTY
	 FROM FACT_TRANSACTIONS AS T1
	 INNER JOIN DIM_MODEL AS T2
	 ON T1.IDModel = T2.IDModel
	 INNER JOIN DIM_MANUFACTURER AS T3
	 ON T2.IDManufacturer = T3.IDManufacturer
	 GROUP BY MANUFACTURER_NAME, MODEL_NAME
     ORDER BY AVG(TOTALPRICE) DESC

--Q5--END

--Q6--BEGIN
     
	 WITH CTE1 AS
	 (
	 SELECT CUSTOMER_NAME, AVG(TOTALPRICE) AS AVG_AMT, DATEPART(YEAR, DATE) AS YR
	 FROM FACT_TRANSACTIONS AS T1
	 INNER JOIN DIM_CUSTOMER AS T2
	 ON T1.IDCustomer = T2.IDCustomer
	 GROUP BY Customer_Name, DATEPART(YEAR, DATE)
     ),	
	 CTE2 AS
	 (
	 SELECT CUSTOMER_NAME, AVG_AMT, YR FROM CTE1
     WHERE YR = '2009' AND AVG_AMT > '500'
	 )
	 SELECT CUSTOMER_NAME, AVG_AMT FROM CTE2 AS X1

--Q6--END
	
--Q7--BEGIN  
	
	SELECT(
	    SELECT TOP 5 MODEL_NAME FROM FACT_TRANSACTIONS AS T1 INNER JOIN DIM_MODEL AS T2
	    ON T1.IDModel = T2.IDModel
	    INNER JOIN DIM_DATE AS T3 ON T3.DATE = T1.DATE
	    WHERE YEAR IN ('2008')
		GROUP BY MODEL_NAME
		ORDER BY SUM(QUANTITY) DESC
	INTERSECT
	     SELECT TOP 5 MODEL_NAME FROM FACT_TRANSACTIONS AS T1 INNER JOIN DIM_MODEL AS T2
	     ON T1.IDModel = T2.IDModel
	     INNER JOIN DIM_DATE AS T3 ON T3.DATE = T1.DATE
	     WHERE YEAR IN ('2009')
		 GROUP BY MODEL_NAME
		 ORDER BY SUM(QUANTITY) DESC
    INTERSECT
	       SELECT TOP 5 MODEL_NAME FROM FACT_TRANSACTIONS AS T1 INNER JOIN DIM_MODEL AS T2
	    ON T1.IDModel = T2.IDModel
	    INNER JOIN DIM_DATE AS T3 ON T3.DATE = T1.DATE
	    WHERE YEAR IN ('2010')
		GROUP BY MODEL_NAME
		ORDER BY SUM(QUANTITY) DESC
		) AS MODEL_NAME

--Q7--END	

--Q8--BEGIN

 
     WITH RANK1 AS 
      (
       SELECT MANUFACTURER_NAME,YEAR(DATE) AS YEAR,
	   DENSE_RANK()OVER (PARTITION BY YEAR(DATE) ORDER BY SUM(TOTALPRICE) DESC) AS RANK
       FROM FACT_TRANSACTIONS AS T1
       INNER JOIN
	   DIM_MODEL AS T2 
       ON T1.IDModel=T2.IDModel
       INNER JOIN DIM_MANUFACTURER AS T3
       ON T2.IDManufacturer=T3.IDManufacturer
       GROUP BY Manufacturer_Name,YEAR(DATE)
       )
    SELECT YEAR, MANUFACTURER_NAME  FROM RANK1
    WHERE YEAR IN ('2009','2010') AND RANK='2'

--Q8--END
--Q9--BEGIN
	
	      SELECT DISTINCT MANUFACTURER_NAME FROM FACT_TRANSACTIONS AS T1
	      INNER JOIN DIM_MODEL AS T2
	      ON T1.IDModel = T2.IDModel
	      INNER JOIN DIM_MANUFACTURER AS T3
	      ON T2.IDManufacturer = T3.IDManufacturer
	      INNER JOIN DIM_DATE AS T4
	      ON T1.Date = T4.DATE
	      WHERE T4.YEAR = '2010'
	 EXCEPT
	      SELECT DISTINCT MANUFACTURER_NAME FROM FACT_TRANSACTIONS AS T1
	      INNER JOIN DIM_MODEL AS T2
	      ON T1.IDModel = T2.IDModel
	      INNER JOIN DIM_MANUFACTURER AS T3
	      ON T2.IDManufacturer = T3.IDManufacturer
	      INNER JOIN DIM_DATE AS T4
	      ON T1.Date = T4.DATE
	      WHERE T4.YEAR = '2009'

--Q9--END

--Q10--BEGIN
	  
	  WITH TOP100 AS
	     (SELECT TOP 100 CUSTOMER_NAME FROM FACT_TRANSACTIONS AS T1
		  INNER JOIN DIM_CUSTOMER AS T2
		  ON T1.IDCustomer = T2.IDCustomer
		  GROUP BY CUSTOMER_NAME
          ORDER BY SUM(TOTALPRICE) DESC),
      YEAR_WISE_SPEND AS
	     (
		 SELECT CUSTOMER_NAME,AVG(TOTALPRICE) AS AVG_SPENT,AVG(QUANTITY) AS AVG_QTY,SUM(TOTALPRICE) AS TOTAL_PRICE,
		 LAG(AVG(TOTALPRICE),1) OVER(PARTITION BY T4.CUSTOMER_NAME ORDER BY T5.YEAR) AS LAG, T5.YEAR AS YEAR
		 FROM FACT_TRANSACTIONS AS T3 
		 INNER JOIN DIM_CUSTOMER AS T4
		 ON T3.IDCustomer = T4.IDCustomer
		 INNER JOIN DIM_DATE AS T5
		 ON T3.Date = T5.DATE
		 WHERE CUSTOMER_NAME IN (SELECT CUSTOMER_NAME FROM TOP100)
		 GROUP BY CUSTOMER_NAME, T5.YEAR
		 )
      SELECT CUSTOMER_NAME, AVG_SPENT, AVG_QTY, YEAR, ((AVG_SPENT-LAG)/AVG_SPENT*100) AS [%AGE_CHANGE]
	  FROM YEAR_WISE_SPEND AS A

--Q10--END
	